<?php

use Drupal\group\Entity\GroupType;
use Drupal\user\Entity\Role;

/**
 * Returns all group roles, excluding roles "Group Admin".
 *
 * @return array
 *   An associative array of role IDs and their labels.
 */
function get_all_group_roles()
{
    $all_roles = [];

    $roles = Role::loadMultiple();
    foreach ($roles as $role_key => $role) {
        $all_roles[$role_key] = $role->label();
    }
    $group_type_entity = GroupType::load('house1');
    if ($group_type_entity) {
        $roles = $group_type_entity->getRoles(FALSE);

        foreach ($roles as $role_key => $role) {

            // Skip this role if it contains "admin"
            // Get all roles excluding the Admin roles.
            if (strpos(strtolower($role->label()), 'admin') !== false) {
                continue;
            }
            $all_roles[$role_key] = $role->label();
        }

        return $all_roles;
    }
}
