<?php
function event_feedback_theme($existing, $type, $theme, $path)
{
    return [
        'event_feedback_page' => [
            'variables' => [
                'node' => NULL,
                'webform' => NULL,
                'message' => NULL,
                'eventDates' => NULL
            ],
            'template' => 'event-feedback-page'
        ],
        'report_page' => [
            'variables' => [
                'header' => null,
                'rows' => [],
                'title' => "",
                'exposed' => null,
                'pager' => null
            ],
            'template' => 'report-page'
        ],
        'report_table' => [
            'variables' => [
                'table_header' => [],
                'table_body' => [],
                'ccount' => 0
            ],
            'template' => 'report-table'
        ]
    ];
}
