find_your_house.settings:
  type: config_object
  label: 'Find Your House Settings'
  mapping:
    go_button:
      type: string
      label: 'Go Button Text'
    group_types:
      type: sequence
      label: 'Group Types'
      sequence:
        type: mapping
        mapping:
          value:
            type: string
            label: 'Group Type Value'
    link_text:
      type: string
      label: 'Link Text'
    link_url:
      type: string
      label: 'Link URL'
