<?php

/**
 * @file
 * Group media library widget module.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\group_media_library_widget\MediaLibraryFieldWidget;
use Drupal\media_library\Plugin\Field\FieldWidget\MediaLibraryWidget;

/**
 * Implements hook_field_widget_single_element_form_alter().
 *
 * Add GroupMediaLibraryState to the media library state.
 */
function group_media_library_field_widget_single_element_form_alter(array &$element, FormStateInterface $form_state, $context): void {
  if ($context['widget'] instanceof MediaLibraryWidget) {
    \Drupal::classResolver(MediaLibraryFieldWidget::class)
      ->formAlter($element, $form_state, $context);
  }
}
