<?php

use Drupal\Core\Form\FormStateInterface;

function pennchas_form_alter_form_alter(array &$form, FormStateInterface $form_state, string $form_id)
{
    if ($form_id === 'user_role_form' || $form_id === 'group_role_add_form' || $form_id === 'group_role_edit_form') {
        pennchas_form_alter_role_form($form, $form_state);
    } else if ($form_id === 'node_room_form' || $form_id === 'node_room_edit_form') {
        $form['field_max_room_booking_duration']['widget'][0]['duration']['#h']['#max'] = 23;
        $form['field_max_room_booking_duration']['widget'][0]['duration']['#h']['#step'] = 1;
        $form['field_max_room_booking_duration']['widget'][0]['duration']['#i']['#max'] = 30;
        $form['field_max_room_booking_duration']['widget'][0]['duration']['#i']['#step'] = 30;
    }
}

function pennchas_form_alter_entity_bundle_field_info_alter(&$fields, $entity_type, $bundle)
{
    if ($bundle === 'reserve_room') {
        if (isset($fields['field_room'])) {
            $fields['field_room']->addConstraint('AllowRoomConstraint');
        }

        if (isset($fields['field_event_schedule'])) {
            $fields['field_event_schedule']->addConstraint('RoomAvailableConstraint');
        }
    }
}

function pennchas_form_alter_role_form(array &$form, FormStateInterface $form_state)
{
    $umbera_roles = [];
    $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('role_category');
    if (!empty($terms)) {
        foreach ($terms as $term) {
            $umbera_roles[$term->name] = $term->name;
        }

        $role = $form_state->getFormObject()->getEntity();
        $existing_umbera_roles = $role->getThirdPartySetting('pennchas_form_alter', 'umbera_roles');

        $form['umbera_roles'] = [
            '#type' => 'checkboxes',
            '#title' => t('Umbera Roles'),
            '#default_value' => $existing_umbera_roles ?: '',
            '#options' => $umbera_roles,
            // '#validate' => ['role_form_validation'],
        ];
        
        $form['actions']['submit']['#submit'][] = 'role_form_submit_handler';
    }
}

function role_form_validation($form, FormStateInterface $form_state)
{
    $form_state->setValue('umbera_roles', $form_state->getValue('umbera_roles'));
}

function role_form_submit_handler(&$form, FormStateInterface $form_state)
{
    $umbera_roles = $form_state->getValue('umbera_roles');
    $umbera_roles = array_filter($umbera_roles);
    $role = $form_state->getFormObject()->getEntity();
    $role->setThirdPartySetting('pennchas_form_alter', 'umbera_roles', $umbera_roles);
    $role->save();
}
