<?php

use Drupal\Core\Database\Query\Condition;
use Drupal\Core\Entity\Query\QueryInterface;
use Drupal\views\Plugin\views\query\Sql;
use Drupal\views\ViewExecutable;
use Drupal\views\Views;

/**
 * Implements hook_page_attachments().
 */
function view_alteration_page_attachments(array &$attachments)
{
  // Attach the custom JavaScript file for AJAX Views pager.
  $attachments['#attached']['library'][] = 'view_alteration/ajax_pager';
}

/**
 * Implements hook_theme().
 */
function view_alteration_theme()
{
  return [
    'ajax_pager' => [
      'version' => '1.0',
      'js' => [
        'js/ajax_pager.js',
      ],
    ],
  ];
}


