<?php

use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Config\Entity\Query\Query;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\Plugin\views\query\Sql;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_page_attachments().
 */
function view_alteration_page_attachments(array &$attachments)
{
    // Attach the custom JavaScript file for AJAX Views pager.
    $attachments['#attached']['library'][] = 'view_alteration/ajax_pager';
}

/**
 * Implements hook_theme().
 */
function view_alteration_theme()
{
    return [
        'ajax_pager' => [
            'version' => '1.0',
            'js' => [
                'js/ajax_pager.js',
            ],
        ],
    ];
}

/**
 * Implements hook_views_data_alter().
 */
function view_alteration_views_data_alter(array &$data)
{
    // dd($data);
    if (isset($data['group_relationship__group_roles']) && isset($data['user__roles'])) {
        $data['users_field_data']['custom_roles_filter'] = [
            'title' => t('Custom Roles filter'),
            'filter' => [
                'title' => t('Custom Roles filter'),
                'help' => t('Custom Roles filter'),
                'field' => 'roles',
                'id' => 'custom_roles_filter',
            ],
        ];
    }
}

function view_alteration_views_query_alter(ViewExecutable $view, Sql $query)
{
    $viewId = $view->id();
    $reportViewIds = [
        'moderation_reports',
        'rooms_reservation_moderation_reports',
        'contents_change_report',
        'contents_delete_report',
        'events_evaluation_report',
        'room_reservation_reports',
        'users_reports',
        'videos_link_report'
    ];
    if (!in_array($viewId, $reportViewIds, true)) {
        return;
    }
    $groupRelationshipColumn = [
        'users_reports' => 'group_relationship_field_data_users_field_data.gid',
        'videos_link_report' => 'group_relationship_field_data_media_field_data.gid',
    ];

    $groups = \Drupal::service('pennchas_common.option_group')->options('house1', false);
    if ($groups) {
        $field = $groupRelationshipColumn[$viewId] ?? 'gcfd.gid';
        $query->addWhere(0, $field, array_keys($groups), 'IN');
    }
}
