_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  advagg: 0
  advagg_css_minify: 0
  announcements_feed: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bootstrap_layout_builder: 0
  bootstrap_styles: 0
  bpmn_io: 0
  breakpoint: 0
  calendar_view: 0
  captcha: 0
  checklistapi: 0
  ckeditor5: 0
  ckeditor5_open_new_tab: 0
  ckeditor_html_embed: 0
  ckeditor_media_resize: 0
  color_field: 0
  comment: 0
  common_utils: 0
  complete_webform_exporter: 0
  conditional_fields: 0
  config: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  csv_serialization: 0
  custom_view_filters: 0
  datetime: 0
  dblog: 0
  devel: 0
  duration_field: 0
  dynamic_page_cache: 0
  easy_email: 0
  eca: 0
  eca_access: 0
  eca_base: 0
  eca_modeller_bpmn: 0
  eca_ui: 0
  eca_user: 0
  editor: 0
  element_class_formatter: 0
  element_class_formatter_responsive_image: 0
  endroid_qr_code: 0
  entity: 0
  entity_clone: 0
  entity_reference_revisions: 0
  event_evaluation: 0
  event_feedback: 0
  feeds: 0
  feeds_log: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  find_your_house: 0
  flexible_permissions: 0
  fullcalendar_view: 0
  gcontent_moderation: 0
  gnode: 0
  group: 0
  group_finder: 0
  group_media_library: 0
  group_media_library_groupmedia: 0
  group_media_library_media_tracker: 0
  group_media_library_widget: 0
  group_permissions: 0
  group_relationship_tokens: 0
  group_role_condition_plugin: 0
  groupmedia: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_resizable: 0
  language: 0
  layout_builder: 0
  layout_builder_block_clone: 0
  layout_builder_blocks: 0
  layout_builder_modal: 0
  layout_builder_restrictions: 0
  layout_builder_restrictions_by_region: 0
  layout_builder_styles: 0
  layout_builder_tabs: 0
  layout_discovery: 0
  link: 0
  linkit: 0
  mailsystem: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  menu_item_group_role_access: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  penchas_block_group_role_condition: 0
  penchas_custom_token: 0
  penchas_group_role_permissions: 0
  penchas_node_alteration: 0
  pennchas_form_alter: 0
  recaptcha_v3: 0
  recreate_block_content: 0
  redirect: 0
  responsive_image: 0
  rest: 0
  search_api: 0
  search_api_db: 0
  search_api_pantheon: 0
  search_api_pantheon_admin: 0
  search_api_solr: 0
  search_api_solr_admin: 0
  section_library: 0
  seo_checklist: 0
  serialization: 0
  shortcut: 0
  simplesamlphp_auth: 0
  simplify_menu: 0
  smart_date: 0
  smart_date_recur: 0
  standard: 0
  svg_image_field: 0
  svg_image_field_media_bundle: 0
  symfony_mailer: 0
  system: 0
  taxonomy: 0
  tb_megamenu: 0
  term_reference_tree: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  twig_attributes: 0
  twig_tweak: 0
  ultimate_cron: 0
  update: 0
  url_alteration: 0
  user: 0
  userprotect: 0
  variationcache: 0
  verf: 0
  view_alteration: 0
  views_aggregator: 0
  views_bootstrap: 0
  views_data_export: 0
  views_fields_combine: 0
  views_list_sort: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_devel: 0
  webform_example_custom_form: 0
  webform_node: 0
  webform_submission_export_import: 0
  webform_ui: 0
  webform_views: 0
  workflows: 0
  pathauto: 1
  externalauth: 10
  views: 10
  paragraphs: 11
  publication_date: 99
theme:
  olivero: 0
  claro: 0
  stable9: 0
  bootstrap_barrio: 0
  penchas: 0
profile: standard
