_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  announcements_feed: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bootstrap_layout_builder: 0
  bootstrap_styles: 0
  breakpoint: 0
  ckeditor5: 0
  color_field: 0
  comment: 0
  config: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  custom_token: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  easy_email: 0
  editor: 0
  entity: 0
  event_calendar: 0
  event_evaluation: 0
  event_feedback: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  find_your_house: 0
  flexible_permissions: 0
  fullcalendar_view: 0
  gcontent_moderation: 0
  gnode: 0
  group: 0
  group_permissions: 0
  group_relationship_tokens: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_resizable: 0
  layout_builder: 0
  layout_builder_blocks: 0
  layout_builder_restrictions: 0
  layout_builder_restrictions_by_region: 0
  layout_discovery: 0
  link: 0
  mailsystem: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  menu_item_role_access: 0
  menu_link_content: 0
  menu_ui: 0
  multiple_fields_remove_button: 0
  mysql: 0
  node: 0
  node_event_form_ext: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  recreate_block_content: 0
  search: 0
  section_library: 0
  shortcut: 0
  simplesamlphp_auth: 0
  smart_date: 0
  smart_date_recur: 0
  standard: 0
  symfony_mailer: 0
  system: 0
  taxonomy: 0
  tb_megamenu: 0
  term_reference_tree: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  ultimate_cron: 0
  update: 0
  user: 0
  variationcache: 0
  views_bootstrap: 0
  views_fields_combine: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_node: 0
  webform_ui: 0
  workflows: 0
  pathauto: 1
  externalauth: 10
  views: 10
theme:
  olivero: 0
  claro: 0
  stable9: 0
  bootstrap_barrio: 0
  penchas: 0
profile: standard
