cloneable_entities:
  - block
  - block_content
  - block_content_type
  - blb_breakpoint
  - blb_layout
  - blb_layout_option
  - captcha_point
  - comment_type
  - comment
  - contact_message
  - contact_form
  - content_moderation_state
  - easy_email
  - easy_email_type
  - eca_model
  - eca
  - editor
  - feeds_feed
  - feeds_subscription
  - feeds_feed_type
  - feeds_import_log
  - field_config
  - field_storage_config
  - file
  - filter_format
  - group_relationship
  - group_config_wrapper
  - group_role
  - group_type
  - group
  - group_relationship_type
  - group_permission
  - image_style
  - configurable_language
  - language_content_settings
  - layout_builder_style
  - layout_builder_style_group
  - linkit_profile
  - media_type
  - media
  - menu_link_content
  - metatag_defaults
  - node
  - node_type
  - path_alias
  - recaptcha_v3_action
  - redirect
  - responsive_image_style
  - rest_resource_config
  - search_api_index
  - search_api_task
  - search_api_server
  - solr_request_dispatcher
  - solr_field_type
  - solr_request_handler
  - solr_cache
  - section_library_template
  - shortcut
  - shortcut_set
  - smart_date_format
  - smart_date_override
  - smart_date_rule
  - mailer_policy
  - mailer_transport
  - action
  - menu
  - taxonomy_vocabulary
  - taxonomy_term
  - tb_megamenu
  - ultimate_cron_job
  - user_role
  - user
  - userprotect_rule
  - webform
  - webform_options
  - webform_submission
  - workflow
  - pathauto_pattern
  - view
  - paragraphs_type
  - paragraph
  - date_format
  - entity_view_display
  - entity_form_display
  - entity_view_mode
  - entity_form_mode
  - base_field_override
