plugins:
  background:
    background_color:
      enabled: 1
    background_media:
      enabled: 0
  typography:
    text_color:
      enabled: 1
    text_alignment:
      enabled: 1
  spacing:
    padding:
      enabled: 1
    margin:
      enabled: 1
  border:
    border:
      enabled: 1
  shadow:
    box_shadow:
      enabled: 1
  animation:
    scroll_effects:
      enabled: 0
block_restrictions:
  - 'inline_block:footer_services'
  - 'inline_block:top_content_section'
  - page_title_block
  - local_tasks_block
