_core:
  default_config_hash: 6xvuojdlZ8-8Q7yJyRldPaE0UK_YijOlDo6HvURmW_E
site_key: 6LeJHJ8qAAAAAApHFIjYa8lypKlaVbf1RxsgdzCj
secret_key: 6LeJHJ8qAAAAALyeRIub9_k4cmszXvAPOkV2Azc6
hide_badge: false
verify_hostname: true
default_challenge: ''
error_message: 'Anti-bot verification failed.'
cacheable: false
library_use_recaptcha_net: false
