_core:
  default_config_hash: 6xvuojdlZ8-8Q7yJyRldPaE0UK_YijOlDo6HvURmW_E
site_key: 6LezWaAqAAAAAJe89jUpHevuVFBmn2A4JIJcfMuP
secret_key: 6LezWaAqAAAAADn_uR9jf-B4a86kj5ZVtIP4OPtF
hide_badge: false
verify_hostname: true
default_challenge: captcha/Math
error_message: 'Captcha verification failed. You may be flagged as a bot. Please refresh the page and try again.'
cacheable: false
library_use_recaptcha_net: false
