_core:
  default_config_hash: RMy8ch2MOT68bCD63OGZQRdMk2pD6UXPEZMuCIisbfs
langcode: en
activate: true
auth_source: default-sp
login_link_display_name: 'Federated login'
login_link_show: true
user_name: eduPersonPrincipalName
unique_id: eduPersonPrincipalName
mail_attr: mail
header_no_cache: false
role:
  population: null
  eval_every_time: false
register_users: true
allow:
  set_drupal_pwd: true
  default_login: true
  default_login_roles:
    administrator: administrator
    chas_student_worker: chas_student_worker
  default_login_users: '1, 47, 48, 49, 50, 3, 41, 6, 42, 38, 32, 24, 39, 28,15, 26, 31'
logout_goto_url: ''
user_register_original: admin_only
sync:
  mail: true
  user_name: true
autoenablesaml: false
debug: false
secure: false
httponly: false
