_core:
  default_config_hash: RMy8ch2MOT68bCD63OGZQRdMk2pD6UXPEZMuCIisbfs
langcode: en
activate: true
auth_source: default-sp
login_link_display_name: 'Pennkey Login'
login_link_show: true
user_name: eduPersonPrincipalName
unique_id: eduPersonPrincipalName
mail_attr: mail
header_no_cache: false
role:
  population: "chas_technology:eduPersonEntitlement,~=,chas_technology|\r\nchas_staff:eduPersonEntitlement,~=,chas_staff|administrator:eduPersonEntitlement,~=,administrator|campus_partner:eduPersonEntitlement,~=,campus_partner|chas_senior_staff:eduPersonEntitlement,~=,chas_senior_staff|faculty:eduPersonEntitlement,~=,faculty|faculty_director:eduPersonEntitlement,~=,faculty_director|house_coordinator:eduPersonEntitlement,~=,house_coordinator|house_director:eduPersonEntitlement,~=,house_director|house_office:eduPersonEntitlement,~=,house_office|resident_advisor:eduPersonEntitlement,~=,ra|student_manager:eduPersonEntitlement,~=,student_manager|student_technology:eduPersonEntitlement,~=,student_technology|dubois_staff:eduPersonEntitlement,~=,facstaff,~=,Du_Bois_CH|dubois_student:eduPersonEntitlement,~=,student,~=,Du_Bois_CH|fh_staff:eduPersonEntitlement,~=,facstaff,~=,Fisher_Hassenfeld_CH|fh_student:eduPersonEntitlement,~=,student,~=,Fisher_Hassenfeld_CH|gregory_staff:eduPersonEntitlement,~=,facstaff,~=,Gregory_CH|gregory_student:eduPersonEntitlement,~=,student,~=,Gregory_CH|harnwell_staff:eduPersonEntitlement,~=,facstaff,~=,Harnwell_CH|harnwell_student:eduPersonEntitlement,~=,student,~=,Harnwell_CH|harrison_staff:eduPersonEntitlement,~=,facstaff,~=,Harrison_CH|harrison_student:eduPersonEntitlement,~=,student,~=,Harrison_CH|hill_staff:eduPersonEntitlement,~=,facstaff,~=,Hill_CH|hill_student:eduPersonEntitlement,~=,student,~=,Hill_CH|kcech_staff:eduPersonEntitlement,~=,facstaff,~=,Kings_Court_English_CH|kcech_student:eduPersonEntitlement,~=,student,~=,Kings_Court_English_CH|lauder_staff:eduPersonEntitlement,~=,facstaff,~=,Lauder_CH|lauder_student:eduPersonEntitlement,~=,student,~=,Lauder_CH|west_staff:eduPersonEntitlement,~=,facstaff,~=,New_CH_West_CH|west_student:eduPersonEntitlement,~=,student,~=,New_CH_West_CH|riepe_staff:eduPersonEntitlement,~=,facstaff,~=,Riepe_CH|riepe_student:eduPersonEntitlement,~=,student,~=,Riepe_CH|rodin_staff:eduPersonEntitlement,~=,facstaff,~=,Rodin_CH|rodin_student:eduPersonEntitlement,~=,student,~=,Rodin_CH|stouffer_staff:eduPersonEntitlement,~=,facstaff,~=,Stouffer_CH|stouffer_student:eduPersonEntitlement,~=,student,~=,Stouffer_CH"
  eval_every_time: false
register_users: true
allow:
  set_drupal_pwd: true
  default_login: true
  default_login_roles:
    authenticated: authenticated
    content_editor: content_editor
    administrator: administrator
    campus_partner: campus_partner
    chas_student_worker: chas_student_worker
    chas_technology: chas_technology
    chas_director: chas_director
    chas_professional_staff: chas_professional_staff
    house_director: house_director
  default_login_users: ''
logout_goto_url: ''
user_register_original: visitors_admin_approval
sync:
  mail: false
  user_name: false
autoenablesaml: false
debug: true
secure: false
httponly: false
