_core:
  default_config_hash: JqYNByWeXZGynyqoPRWQIjp3VcQhuoyq5WlM-7YzBvI
smtp_on: true
smtp_host: smtp-relay.upenn.edu
smtp_hostbackup: ''
smtp_port: '25'
smtp_protocol: standard
smtp_autotls: true
smtp_timeout: 30
smtp_username: smtp-relay/collegehouses.upenn.edu
smtp_password: oktad;Kneb63GlovUthid
smtp_from: chas@collegehouses.upenn.edu
smtp_fromname: 'Penn CHAS'
smtp_client_hostname: collegehouses.upenn.edu
smtp_client_helo: ''
smtp_allowhtml: true
smtp_test_address: ''
smtp_reroute_address: ''
smtp_debugging: false
smtp_debug_level: 2
prev_mail_system: php_mail
smtp_keepalive: false
