<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;
use Drupal\node_form_extension\Plugin\RoomReservationHandler;

function node_form_extension_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state, string $form_id)
{
    if($form_id === 'node_room_form') {
        // dd($form['field_max_room_booking_duration']['widget'][0]['value']);
    }
}

function node_form_extension_entity_presave(EntityInterface $entity)
{
    if ($entity instanceof NodeInterface && $entity->bundle() === 'reserve_room') {
        $handler = new RoomReservationHandler();
        $handler->handlePreSave($entity);
    }
}

function node_form_extension_node_insert(Node $node)
{
    if ($node->getType() === 'reserve_room') {
        $eventHandler = new RoomReservationHandler();
        $eventHandler->handleInsert($node);
    }
}

// function node_form_extension_node_update(\Drupal\node\Entity\Node $node)
// {
//     if ($node->getType() === 'chas_event') {
//         $eventHandler = new RoomReservationHandler();
//         $eventHandler->handleEventUpdate($node);
//     }
// }