<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\taxonomy\Entity\Term;

function config_form_extension_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
    if ($form_id === 'user_role_form' || $form_id === 'group_role_add_form' || $form_id === 'group_role_edit_form') {

        $categories = [];
        $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('role_category');
        if(!empty($terms)){
          foreach ($terms as $term) {
              $categories[$term->tid] = $term->name;
          }

          $role = $form_state->getFormObject()->getEntity();
          $existing_categories = $role->getThirdPartySetting('umbera_roles', 'target_id');

          $form['umbera_roles'] = [
              '#type' => 'checkboxes',
              '#title' => t('Umbera Roles'),
              '#default_value' => $existing_categories ?: '',
              '#options' => $categories,
          ];

          if($form['actions']){
            foreach (array_keys($form['actions']) as $action) {
                if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
                    $form['actions'][$action]['#submit'][] = 'role_form_submit_handler';
                }
            }
          }
        }
    }
}

function role_form_submit_handler(&$form, FormStateInterface $form_state)
{
    $role_categories = $form_state->getValue('umbera_roles');
    $role_categories = array_filter($role_categories);
    $role = $form_state->getFormObject()->getEntity();
    $role->setThirdPartySetting('umbera_roles', 'target_id', $role_categories);
    $role->save();
}
