<?php

use Drupal\group\Entity\Group;
use Drupal\node\NodeInterface;

/**
 * Implements hook_form_alter()
 */
function node_event_form_ext_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state, string $form_id)
{

    if ($form_id === 'node_chas_event_form' || $form_id === 'node_chas_event_edit_form') {
        $form['field_audience_floor']['#states'] = [
            'visible' => [
                ':input[name="field_intended_audience[floors_residents]"]' => [
                    'checked' => true
                ]
            ]
        ];
        $form['field_audience_floor']['widget']['#required'] = [
            ':input[name="field_intended_audience[floors_residents]"]' => [
                'checked' => true
            ]
        ];

        // Enable program community field
        $form['field_program_communities']['#states'] = [
            'visible' => [
                ':input[name="field_intended_audience[program_community]"]' => [
                    'checked' => true
                ]
            ],
            'required' => [
                ':input[name="field_intended_audience[program_community]"]' => [
                    'checked' => true
                ]
            ]
        ];

        if ($form_id === 'node_chas_event_form') {
            $form['field_college_houses']['#states'] = [
                'checked' => true,
            ];
        }

        // Enable Other field
        $form['field_intended_audience_other']['#states'] = [
            'visible' => [
                ':input[name="field_intended_audience[other]"]' => [
                    'checked' => true
                ]
            ],
            'required' => [
                ':input[name="field_intended_audience[other]"]' => [
                    'checked' => true
                ]
            ]
        ];

        // Enable marketing releated fields for audience options
        $form['field_intended_audience_image']['#states'] = [
            'visible' => [
                [
                    ':input[name="field_intended_audience[all_house_residents]"]' => ['checked' => true],
                ],
                [
                    ':input[name="field_intended_audience[multiple_college_houses]"]' => ['checked' => true]
                ],
                [
                    ':input[name="field_intended_audience[all_first_year_students]"]' => ['checked' => true]
                ],
                [
                    ':input[name="field_intended_audience[all_second_year_students]"]' => ['checked' => true]
                ],
                [
                    ':input[name="field_intended_audience[all_upper_year_students]"]' => ['checked' => true]
                ]
            ],
        ];

        $form['field_intended_audience_attach']['#states'] = [
            'visible' => [
                [
                    ':input[name="field_intended_audience[all_house_residents]"]' => ['checked' => true],
                ],
                [
                    ':input[name="field_intended_audience[multiple_college_houses]"]' => ['checked' => true]
                ],
                [
                    ':input[name="field_intended_audience[all_first_year_students]"]' => ['checked' => true]
                ],
                [
                    ':input[name="field_intended_audience[all_second_year_students]"]' => ['checked' => true]
                ],
                [
                    ':input[name="field_intended_audience[all_upper_year_students]"]' => ['checked' => true]
                ]
            ],
        ];

        $form['field_marketing_blurb']['#states'] = [
            'visible' => [
                [
                    ':input[name="field_intended_audience[all_house_residents]"]' => ['checked' => true],
                ],
                [
                    ':input[name="field_intended_audience[multiple_college_houses]"]' => ['checked' => true]
                ],
                [
                    ':input[name="field_intended_audience[all_first_year_students]"]' => ['checked' => true]
                ],
                [
                    ':input[name="field_intended_audience[all_second_year_students]"]' => ['checked' => true]
                ],
                [
                    ':input[name="field_intended_audience[all_upper_year_students]"]' => ['checked' => true]
                ]
            ],
        ];

        // Enbale outcome fields
        $form['field_intended_outcomes_remarks']['#states'] = [
            'visible' => [
                [
                    ':input[name="field_intended_outcomes[learn_a_skill]"]' => ['checked' => true],
                ],
                [
                    ':input[name="field_intended_outcomes[gain_information]"]' => ['checked' => true]
                ],
                [
                    ':input[name="field_intended_outcomes[connect_with_peers]"]' => ['checked' => true]
                ],
                [
                    ':input[name="field_intended_outcomes[connect_with_resource]"]' => ['checked' => true]
                ],
                [
                    ':input[name="field_intended_outcomes[connect_with_faculty]"]' => ['checked' => true]
                ],
                [
                    ':input[name="field_intended_outcomes[engage_in_an_activity]"]' => ['checked' => true]
                ]
            ],
        ];

        $form['#attached']['library'][] = 'node_event_form_ext/event_listeners';
        if ($form_id === 'node_chas_event_form') {
            $form['#attached']['library'][] = 'node_event_form_ext/default_select';
        }
    }
}

function node_event_form_ext_entity_presave(Drupal\Core\Entity\EntityInterface $entity)
{
    if ($entity->bundle() === 'chas_event' && $entity instanceof NodeInterface) {
        $houses = $entity->get('field_college_houses')->getValue();
        if (can_by_pass_moderation(array_column($houses, 'target_id'))) {
            $entity->setPublished(true);
            $entity->set('moderation_state', 'published');
        }
    }
}

function node_event_form_ext_node_insert(\Drupal\node\Entity\Node $node)
{
    if ($node->getType() === 'chas_event') {
        \Drupal::messenger()->deleteAll();
        $houses = $node->get('field_college_houses')->getValue();
        foreach ($houses as $house_details) {
            $house = \Drupal\group\Entity\Group::load($house_details['target_id']);
            $existing_relationship = $house->getRelationshipsByEntity($node);
            if (empty($existing_relationship)) {
                $house->addRelationship($node, 'group_node:' . $node->getType());
            }
        }

        $message = t('Your event has been accepted and published.');
        if (!can_by_pass_moderation(array_column($houses, 'target_id'))) {
            $message = t('Your event has been submitted and there is a possible three day wait time for approval.');
            notify_event_create($node);
        }

        \Drupal::messenger()->addStatus($message);
    }
}

function node_event_form_ext_node_update(\Drupal\node\Entity\Node $node)
{
    if ($node->getType() === 'chas_event') {
        $existing_houses = $node->original->get('field_college_houses')->getValue();
        $houses = $node->get('field_college_houses')->getValue();
        $result = process_houses_diff($existing_houses, $houses);

        if ($result['new']) {
            foreach ($result['new'] as $house_id) {
                $house = \Drupal\group\Entity\Group::load($house_id);
                $existing_relationship = $house->getRelationshipsByEntity($node);
                if (empty($existing_relationship)) {
                    $house->addRelationship($node, 'group_node:' . $node->getType());
                }
            }
        }
        if ($result['remove']) {
            foreach ($result['remove'] as $house_id) {
                $house = \Drupal\group\Entity\Group::load($house_id);
                $relationships = $house->getRelationshipsByEntity($node);
                if (!empty($relationships)) {
                    array_walk($relationships, function (\Drupal\group\Entity\GroupRelationshipInterface $rel) {
                        $rel->delete();
                    });
                }
            }
        }
    }
}

function process_houses_diff($existing_houses, $new_houses)
{
    $existing_houses_id = array_flip(array_column($existing_houses, 'target_id'));
    $new_houses_id = array_column($new_houses, 'target_id');

    $new_houses_rel = [];
    $house_rel_del = [];

    foreach ($new_houses_id as $house_id) {
        if (isset($existing_houses_id[$house_id])) {
            unset($existing_houses_id[$house_id]);
        } else {
            $new_houses_rel[] = $house_id;
        }
    }

    if ($existing_houses) {
        $house_rel_del = array_flip($existing_houses_id);
    }

    return [
        'new' => $new_houses_rel,
        'remove' => $house_rel_del
    ];
}

function can_by_pass_moderation($group_ids)
{
    $current_user = \Drupal::currentUser();
    $group_memberships = \Drupal::service('group.membership_loader')->loadByUser($current_user);
    if (count($group_memberships) > 0) {
        foreach ($group_ids as $group_id) {
            $group = Group::load($group_id);
            if ($group->hasPermission('use editorial transition publish', $current_user)) {
                return true;
            }
        }
        return false;
    }

    return $current_user->hasPermission('use editorial transition publish');
}

/**
 * Send notification to users
 */
function notify_event_create($node)
{
    $mail_service = \Drupal::service('node_event_form_ext.mail_service');
    $mail_service->notify($node);
}
