<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\taxonomy\Entity\Term;

function role_extend_form_user_role_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
    if ($form_id === 'user_role_form') {

        $categories = [];
        $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('role_category');

        foreach ($terms as $term) {
            $categories[$term->tid] = $term->name;
        }

        $role = $form_state->getFormObject()->getEntity();
        $existing_categories = $role->getThirdPartySetting('role_extend', 'role_categories');

        $form['role_categories'] = [
            '#type' => 'checkboxes',
            '#title' => t('Categories'),
            '#default_value' => $existing_categories ?: '',
            '#options' => $categories
        ];
        // $form['#submit'][] = 'role_extend_submit_handler';
        foreach (array_keys($form['actions']) as $action) {
            if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
                $form['actions'][$action]['#submit'][] = 'role_extend_submit_handler';
            }
        }
    }
}

function role_extend_submit_handler(&$form, FormStateInterface $form_state)
{
    $role_categories = $form_state->getValue('role_categories');
    $role = $form_state->getFormObject()->getEntity();
    $role->setThirdPartySetting('role_extend', 'role_categories', $role_categories);
    $role->save();
}
